name: run-blazemeter-test-actions-workflow
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  testid: "10626081"
  inputallfiles: "/github/workspace/Supporting Files"
  Uploadfilechk: "true"
  env_variable: '{"bearerToken": "\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\"", "pass": "\"Test@123456\""}'

  
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: blazerunner-g/BlazeAction@v7.9.6
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          inputallfiles: ${{env.inputallfiles}}
          Uploadfilechk: ${{env.Uploadfilechk}}
          env_variable: ${{env.env_variable}}
      - name: setValue
        id:  random-color-generator
        run: echo '::set-output name=SELECTED_COLOR::green'
       
  on-success:
    runs-on: ubuntu-latest
    needs:  run-existing-test
    steps:
      - name: Get color
        run: echo "The selected color is ${{ needs.random-color-generator.outputs.SELECTED_COLOR }}"
          
  


