name: run-blazemeter-test-actions-workflow
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  createtest: "true"
  inputstartfile: "BlazeDemo.jmx"
  testname: "GithubAction-D93-taurus-yaml"
  projectid: "961236"
  totalusers: "10"
  duration: "3"
  rampup: "1"
  ContinuePipeline: "false"
  showtaillog: "false"
  
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: blazerunner-g/BlazeAction@v7.9.6
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          createtest: ${{env.createtest}}
          inputstartfile: ${{env.inputstartfile}}
          testname: ${{env.testname}}
          projectid: ${{env.projectid}}
          totalusers: ${{env.totalusers}}
          duration: ${{env.duration}}
          rampup: ${{env.rampup}}
          ContinuePipeline: ${{env.ContinuePipeline}}
          showtaillog: ${{env.showtaillog}}
