name: run-blazemeter-test-actions-workflow
env:
  apikey: "38e53fd821771b102b5bfddc"
  Apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  createtest: "true"
  inputstartfile: BlazeDemo.jmx
  testname: "GithubAction-D71-taurus-yaml"
  projectid: "961236"
  
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: dnyanehblazerunner/BlazeAction@v7.9.4
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          createtest: ${{env.createtest}}
          inputstartfile: ${{env.inputstartfile}}
          testname: ${{env.testname}}
          projectid: ${{env.projectid}}

