name: run-blazemeter-test-actions-workflow
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  testid: "10486100" # P 10127108 F 10129962 
  workspaceid: "838258" #not required
  datamodelid: "8df6aaaf-d1ac-56a1-a2d5-bba0ecbabff9" #not required
#   modeldata: '{"email": "\"test@mailinator.com\"", "password": "\"123456\""}'
  modeldata: '{"url": "\"https://blazedemo123.com/\""}'
  createtest: "false"
  inputstartfile: "BlazeDemoTest_1.jmx"
  testname: "GithubAction-D03"
  projectid: "961236"
  jmeterproperties: "test=test123"
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        #uses: ./ # Uses an action in the root directory
        uses:  dnyanehblazerunner/BlazeAction@v7
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          #modeldata: ${{ toJSON(env.modeldata) }}
          continuepipeline: "false"
          jmeterproperties: ${{env.jmeterproperties}}
#           createtest: ${{env.createtest}}
#           inputstartfile: ${{env.inputstartfile}}
#           testname: ${{env.testname}}
#           projectid: ${{env.projectid}}





