name: run-blazemeter-test-actions-workflow
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  testid: "10690918"
  jmeterproperties: "test=githubaction123,test1=githubaction2,test2=githubaction3" 
  ContinuePipeline: "false"
  showtaillog: "false"
  reportname: "new_script_taurus"
  note: "new_test_script_taurus"
 
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: BlazeRunner-BZR/Github-Action@v3
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          jmeterproperties: ${{env.jmeterproperties}}
          ContinuePipeline: ${{env.ContinuePipeline}}
          showtaillog: ${{env.showtaillog}}
          reportname: ${{env.reportname}}
          note: ${{env.note}}
