name: Github-Action-Demo
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  testid: "10615531"#"9535217"
  ContinuePipeline: "false"
  showtaillog: "false"
   
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run Blazemeter test
      uses: blazerunner-g/BlazeAction@v7.9.7
      id: run-test
      with:
        apikey: ${{env.apikey}}
        apisecret: ${{env.apisecret}}
        testid: ${{env.testid}}
        ContinuePipeline: ${{env.ContinuePipeline}}
        showtaillog: ${{env.showtaillog}} 
    - name: powershell
      id: identify
      shell: pwsh
      run: |
        $jsonResult = Get-Content -Path jsonResult
        echo "::set-output name=jsonResult::$jsonResult"
    outputs:
      jsonResult: ${{ steps.identify.outputs.jsonResult }}
      
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: "Get Variable From first Job"
        run: |
          echo "Json Result : $jsonResult"
        env:
          jsonResult: ${{ needs.first-job.outputs.jsonResult }}
