name: run-blazemeter-test-actions-workflow
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  testid: "10625965"
  ContinuePipeline: "false"
  showtaillog: "false"
              
on: push
  
jobs:
  git-sync:
    runs-on: ubuntu-latest
    #runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: blazerunner-g/BlazeAction@v7.9.7
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          ContinuePipeline: ${{env.ContinuePipeline}}
          showtaillog: ${{env.showtaillog}}
      - run: |
            echo 'The triggering workflow passed'
            echo 'api key : $apikey'
            echo $apikey
            echo 'api key 1 : ${{ env.apikey }}'
            echo 'env variable : $envTestVar'
            echo $envTestVar
            echo $env.envTestVar
            echo $Env:envTestVar
            echo 'env variable : ${{ env.envTestVar }}'
            echo 'env variable1 : $envTestVar1'
            echo $envTestVar1
            echo $env.envTestVar1
            echo $Env:envTestVar
            echo 'env variable1 : ${{ env.envTestVar1 }}'
            echo $envTestVar2
            echo $env.envTestVar2
            echo $Env:envTestVar
            echo 'env variable2 : $envTestVar2'
            echo 'env variable2 : ${{ env.envTestVar2 }}'
             
  on-success:
    needs: git-sync
    runs-on: ubuntu-latest
    #runs-on: windows-latest
    steps: 
      - run: |
            echo 'The triggering workflow passed'
            echo 'api key : $apikey'
            echo $apikey
            echo 'api key 1 : ${{ env.apikey }}'
            echo 'env variable : $envTestVar'
            echo $envTestVar
            echo $env.envTestVar
            echo $Env:envTestVar
            echo 'env variable : ${{ env.envTestVar }}'
            echo 'env variable1 : $envTestVar1'
            echo $envTestVar1
            echo $env.envTestVar1
            echo $Env:envTestVar
            echo 'env variable1 : ${{ env.envTestVar1 }}'
            echo $envTestVar2
            echo $env.envTestVar2
            echo $Env:envTestVar
            echo 'env variable2 : $envTestVar2'
            echo 'env variable2 : ${{ env.envTestVar2 }}'
    
# on: push
# jobs:
#   run-existing-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.4
#       - name: Run Blazemeter test
#         uses: blazerunner-g/BlazeAction@v7.9.7
#         id: run-test
#         with:
#           apikey: ${{env.apikey}}
#           apisecret: ${{env.apisecret}}
#           testid: ${{env.testid}}
#           ContinuePipeline: ${{env.ContinuePipeline}}
#           showtaillog: ${{env.showtaillog}}
#           #Uploadfilechk: ${{env.Uploadfilechk}}
#           #inputstartfile: ${{env.inputstartfile}}
#       - run: |
#             echo ${{ env.BlazeMeterPublicURL }}
#             echo ${{ secrets.BlazeMeterPublicURL }}
            
