name: Github-Action-Demo
env:
  apikey: ''
  apisecret: ''
  testid: ''
  ContinuePipeline: ''
  showtaillog: ''
  env_variable: ''
  inputstartfile: ''
  Uploadfilechk: ''
   
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run Blazemeter test
      uses: BlazeRunner-BZR/Github-Action@v3
      id: run-test
      with:
        apikey: ${{env.apikey}}
        apisecret: ${{env.apisecret}}
        testid: ${{env.testid}}
        ContinuePipeline: ${{env.ContinuePipeline}}
        showtaillog: ${{env.showtaillog}} 
        env_variable: ${{env.env_variable}}
        Uploadfilechk: ${{env.Uploadfilechk}}
        inputstartfile: ${{env.inputstartfile}}
