name: Github-Action-Demo
env:
  apikey: "38e53fd821771b102b5bfddc"
  apisecret: "c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50"
  testid: "9535217" #"9535217"
  ContinuePipeline: "false"
  showtaillog: "false"
  
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run Blazemeter test
      uses: blazerunner-g/BlazeAction@v7.9.7
      id: run-test
      with:
        apikey: ${{env.apikey}}
        apisecret: ${{env.apisecret}}
        testid: ${{env.testid}}
        ContinuePipeline: ${{env.ContinuePipeline}}
        showtaillog: ${{env.showtaillog}} 
    - name: Set Variable  
      id: identify
      run: |
        export JSON_DATA='{"test":"test12334545"}'
        echo "::set-output name=json_data::${JSON_DATA}"
    - name: powershell
      id: identify1
      shell: pwsh
      run: |
        $result = Get-Content -Path Test
        echo "::set-output name=testResult::$result"
    outputs:
      json_data: ${{ steps.identify.outputs.json_data }}
      json_data1: ${{ steps.identify1.outputs.testResult }}
      
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: "Get Variable From first Job"
        run: |
          echo "first job data $Json_Data"
          echo "Test Result output $testResult"
        env:
          Json_Data: ${{ needs.first-job.outputs.json_data }}
          Json_data1: ${{ needs.first-job.outputs.testResult }}
